  GOLD CONFIGURATION FILE

  AUTOMATIC SETTINGS
autoscale = 2

  POPULATION
popsiz = auto
select_pressure = auto
n_islands = auto
maxops = auto
niche_siz = auto

  GENETIC OPERATORS
pt_crosswt = auto
allele_mutatewt = auto
migratewt = auto

  FLOOD FILL
radius = 12
origin = -3.2010 1.1170 9.3050
do_cavity = 1
floodfill_atom_no = 0 
floodfill_center = point

  DATA FILES
ligand_data_file /home/yuchen/or/VS4B/LigandScout/MOR/8efo_8qy_mini/screening.sdf 10 xstartxendx
param_file = DEFAULT
set_ligand_atom_types = 1
set_protein_atom_types = 0
directory = /home/yuchen/or/VS4B/LigandScout/MOR/8efo_8qy_mini/docking/output/xnumberx
tordist_file = DEFAULT
make_subdirs = 0
save_lone_pairs = 1
fit_points_file = fit_pts.mol2
read_fitpts = 0

  FLAGS
internal_ligand_h_bonds = 0
flip_free_corners = 1
match_ring_templates = 1
flip_amide_bonds = 1
flip_planar_n = 1 flip_ring_NRR flip_ring_NHR
flip_pyramidal_n = 1
rotate_carboxylic_oh = flip
use_tordist = 1
postprocess_bonds = 1
rotatable_bond_override_file = DEFAULT
solvate_all = 1

  TERMINATION
early_termination = 1
n_top_solutions = 3
rms_tolerance = 1.5

  CONSTRAINTS
force_constraints = 0

  COVALENT BONDING
covalent = 0

  SAVE OPTIONS
save_score_in_file = 1
save_protein_torsions = 0
concatenated_output = 8efo_8qy_dock.sdf
clean_up_option delete_all_solutions
clean_up_option delete_redundant_log_files
clean_up_option delete_empty_directories
output_file_format = MACCS

  FITNESS FUNCTION SETTINGS
initial_virtual_pt_match_max = 3
relative_ligand_energy = 1
gold_fitfunc_path = plp
score_param_file = DEFAULT

write_options = NO_LOG_FILES NO_LINK_FILES NO_RNK_FILES NO_BESTRANKING_LST_FILE NO_GOLD_LIGAND_MOL2_FILE NO_LGFNAME_FILE NO_PLP_MOL2_FILES NO_PID_FILE NO_SEED_LOG_FILE NO_GOLD_ERR_FILE NO_FIT_PTS_FILES NO_GOLD_LOG_FILE

  PROTEIN DATA
protein_datafile = /home/yuchen/or/VS4B/struct/from_opm/MOR/8efo_aligned_prot.pdb


